services:
  runner:
    build:
      context: .
      dockerfile: runner/Dockerfile
    volumes:
      - ./runner:/runner
    ports:
      - "3000:3000" # Expose the website on port 3000
    networks:
      - app-network

  website:
    build:
      context: .
      dockerfile: website/Dockerfile
    volumes:
      - ./website/src:/app
    ports:
      - "5099:5099" # Expose the website on port 3000
    depends_on:
      - runner # The website depends on runner being up
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
